/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "niippmbpfgajmeycpikp"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5paXBwbWJwZmdham1leWNwaWtwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgwNzE0OTYsImV4cCI6MjA4MzY0NzQ5Nn0.V-USTd42b-fbw5fSYOj-4ceR6_ujdeZ9Be4vnOE24Hs"